#!/bin/sh -xv

HOSTS="
halko.pc.infrahip.net
netherstorm.infrahip.net
terokkar.infrahip.net
shadowmoon.infrahip.net
stonebreaker.infrahip.net
hellfire.infrahip.net
ironforge.infrahip.net
nagrand.infrahip.net
zangarmash.infrahip.net
blacktemple.infrahip.net
"

COMMANDS="
cd /tmp;
sudo rm -rf main;
rm hipl.tar.gz;
wget http://hipl.hiit.fi/hipl/hipl.tar.gz &&
tar xvzf hipl.tar.gz &&
cd main &&
./autogen.sh &&
./configure &&
make bin syncrepo"

#set -e

# FC11-i386           hipserver (real host)
# Ubuntu 8.10, i386   terokkar.infrahip.net
# Ubuntu 8.10, amd64  halko.pc.infrahip.net (real host)
# F10-x86_64	      nagrand.infrahip.net
# F12-x86_64	      shadowmoon.infrahip.net
# CentOS-5.4 i386     hellfire.infrahip.net
# CentOS-5.4 x86_64   zangarmash.infrahip.net
# --
# F10-i386		  ironforge.infrahip.net
# f12-i386		  netherstorm.infrahip.net
# fc11-x86_64             stonebreaker
# fc11-i386               blacktemple
#

if test $# != 0
then
    HOSTS="$@"
fi

echo "--- Pinging all hosts ---"

for HOST in $HOSTS
do
    ping -c 2 $HOST
done

echo "--- Executing command on each host ---"

time for HOST in $HOSTS
do
    echo "--- Host: $HOST ---"
    ping -c 2 $HOST
    if test $? = 0
    then
	ssh $HOST $COMMANDS
    else
	echo "Not responding, skipping"
    fi
done
