#!/bin/sh

set -e

PATH=/p/bin:$PATH

TMP_DIR=~/.bzr-hipl-cache
BRANCH=trunk
WWW_DIR=/var/www/infrahip/html/hipl
OUTPUT_FILE=$WWW_DIR/hipl.tar.gz
CHANGE_LOG_FILE=$TMP_DIR/ChangeLog

if test -x  $TMP_DIR; then
    cd $TMP_DIR/hipl-bzr/$BRANCH
    bzr update
else
    mkdir $TMP_DIR
    cd $TMP_DIR
    bzr init-repo hipl-bzr
    cd hipl-bzr
    bzr checkout lp:hipl $BRANCH
    cd $BRANCH
fi

VERSION=$(grep '^AC_INIT' configure.ac | cut -d'[' -f 3 | cut -d']' -f1)

# Generate a ChangeLog file
bzr log > $CHANGE_LOG_FILE

# Make a HIPL tarball
autoreconf --install
./configure --sysconfdir=/etc
make dist

# Add ChangeLog file to tarball and rename to "trunk"
tar xzf hipl-${VERSION}.tar.gz
mv hipl-${VERSION} trunk
cp $CHANGE_LOG_FILE trunk/doc
tar czf hipl.tar.gz trunk
chmod a+r hipl.tar.gz

# Move tarball and ChangeLog to web directory
mv hipl.tar.gz $WWW_DIR
mv $CHANGE_LOG_FILE $WWW_DIR

# Remove temporary files
rm -rf hipl-${VERSION} trunk
