#!/bin/sh

set -e

TMP_DIR=~/.bzr-hipl-cache
BRANCH=trunk
WWW_DIR=/var/www/infrahip/html/hipl

if test -x  $TMP_DIR; then
    cd $TMP_DIR/hipl-bzr/$BRANCH
    bzr update
else
    mkdir $TMP_DIR
    cd $TMP_DIR
    bzr init-repo hipl-bzr
    cd hipl-bzr
    bzr checkout -q lp:hipl $BRANCH
    cd $BRANCH
fi

VERSION=$(grep '^AC_INIT' configure.ac | cut -d'[' -f 3 | cut -d']' -f1)
TARBALL=hipl-${VERSION}.tar.gz

# Make a HIPL tarball
autoreconf --install
./configure --sysconfdir=/etc
make dist

# Add ChangeLog file to tarball
tar xzf $TARBALL
bzr log > hipl-${VERSION}/doc/ChangeLog
tar czf $TARBALL hipl-${VERSION}
chmod a+r $TARBALL

# Move tarball and ChangeLog to web directory
mv $TARBALL hipl-${VERSION}/doc/ChangeLog $WWW_DIR
ln -sf $WWW_DIR/$TARBALL $WWW_DIR/hipl.tar.gz

make doxygen
rm -rf $WWW_DIR/doxygen
mv doc/doxy/html $WWW_DIR/doxygen

make doc/HOWTO.html
cp doc/HOWTO.html doc/*.png $WWW_DIR/manual
touch $WWW_DIR/manual/DO_NOT_EDIT_THESE_MANUALLY.GENERATED_AUTOMATICALLY

# Remove temporary files
rm -rf hipl-${VERSION} trunk
