#!/bin/sh

######################## about ##############################################
#
# purpose: make a tar file from a directory/file and
#          copy it to a remote host using ssh
# author:  Miika Komu, miika@iki.fi
# usage:   see $USAGE
# licence: MIT (Expat)
#
# Copyright (c) 2010 Aalto University and RWTH Aachen University.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

######################## functions ##########################################

# purpose: print an error message and exit with an error code
# params:  error message
# depends: $SCRIPTNAME
#
die() {
  echo "$@"
  exit 1
}

######################## global variables ###################################

USAGE="usage: remotebackup <src_dir> <user@remote_host:remote_dir/dst_filename>"

SSH="/usr/bin/ssh"
TAR="/bin/tar"
# note: using gz compression, because bz2 puts garbage in the eof
TAR_OPTS="--rsh-command=$SSH -cvzf"
SRC_DIR="$1"
REMOTE_DST="$2"

######################## main program #######################################

if [ $# != 2 ]
then
    die "$USAGE"
fi

$TAR $TAR_OPTS $REMOTE_DST $SRC_DIR
