#!/bin/sh

BZR_HIPL_CACHE=~/.bzr-hipl-cache/hipl-bzr
BRANCH=trunk
TMP_DIR=~/.hipl.howto.tmp.dir
WWW_DIR=/var/www/infrahip/html/hipl/manual

set -e

mkdir -p $TMP_DIR $WWW_DIR

touch $WWW_DIR/DO_NOT_EDIT_THESE_MANUALLY.GENERATED_AUTOMATICALLY
cp -r $BZR_HIPL_CACHE/$BRANCH/doc $TMP_DIR
cd $TMP_DIR/doc
xmlto -o manual html HOWTO.xml
cp -r manual/* $WWW_DIR
