#!/bin/sh

# Note: hipfw must be currently started after hipd (runlevel 20)
#update-rc.d hipfw defaults 
update-rc.d hipfw multiuser 21

echo "invoke-rc.d --quiet hipfw start" | at now + 2 min 2>/dev/null 
echo "hip firewall starts in two minutes"

