#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=65
STOP=65

HIPD_OPTS="-bkN"

start() {
    echo -n "Starting hipd"
    hipd ${HIPD_OPTS}
    echo "."
}

restart() {
    echo -n "Restarting hipd"
    # if hipd is running, give it 5 seconds to exit gracefully
    killall hipd && env sleep 5
    hipd ${HIPD_OPTS}
    echo "."
}

stop() {
    echo -n "Stopping hipd"
    killall hipd
    echo "."
}
