#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=65
STOP=65

HIPFW_START='hipfw -kb'

start() {
    echo -n "Starting hipfw"
    ${HIPFW_START}
    echo "."
}

restart() {
    echo -n "Restarting hipfw"
    # if hipfw is running, give it 2 seconds to exit gracefully
    killall hipfw 2>/dev/null && env sleep 2
    ${HIPFW_START}
    echo "."
}

stop() {
    echo -n "Stopping hipfw"
    killall hipfw 2>/dev/null
    echo "."
}
