#!/bin/sh -e

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

if test -d /etc/daemontools/service
then
  echo '/etc/daemontools/service exists. I assume that svscan is already running.'
  exit 0
fi

echo 'Creating /etc/daemontools/service...'
mkdir -p /etc/daemontools/service

if test -r /etc/inittab
then
  /usr/sbin/setlock /etc/inittab package/run.inittab
else
  /usr/sbin/setlock /etc/rc.local package/run.rclocal
fi
