#!/bin/sh

########################
# Configuration

# wireless device
ETH="eth1"
# network prefix
PREFIX="192.168.6."
# first IP address (host part)
IP1="26"
# second IP address (host part)
IP2="23"
# gateway IP address
GW="29"
# netmask for the new route
NETMASK="255.255.255.0"
# destination network for the new route
DESTINATION="192.168.5.0"


########################
# Script

if [ `whoami` != "root" ]; then
	echo "You must be root to run this script!"
	exit 1
fi

OLD_IP=`ip addr show $ETH|grep $PREFIX|sed "s/.*inet \($PREFIX[0-9]*\).*/\1/g"`
if [ "$OLD_IP" = "$PREFIX$IP1" ]; then
	NEW_IP="$PREFIX$IP2"
else
	NEW_IP="$PREFIX$IP1"
fi

echo "switching $ETH IP from $OLD_IP to $NEW_IP"
ifconfig $ETH $NEW_IP up
route add -net "$DESTINATION netmask $NETMASK gw $PREFIX$GW

