Document: hipl
Title: Debian hipl Manual
Author: <insert document author here>
Abstract: This manual describes what hipl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hipl/hipl.sgml.gz

Format: postscript
Files: /usr/share/doc/hipl/hipl.ps.gz

Format: text
Files: /usr/share/doc/hipl/hipl.text.gz

Format: HTML
Index: /usr/share/doc/hipl/html/index.html
Files: /usr/share/doc/hipl/html/*.html
