#!/bin/sh

MAJOR=1
MINOR=0
VERSION="$MAJOR.$MINOR"
RELEASE=1
SUFFIX="-$VERSION-$RELEASE"

error_cleanup()
{
 if [ -n "$PKGDIR" -a -d "$PKGDIR" ];then
   echo "removing '$PKGDIR'"
   rm -rf "$PKGDIR"
 fi
}

echo "** Creating the directory structure and files for building the"
echo "** source package needed for RPM package containing HIPL"
echo "** user space software"
echo "**"
echo "** Version $VERSION (release $RELEASE)"
echo "**"

PKGROOT="`pwd`"
cd ../../
HIPL=`pwd`
echo "** Using directory '$HIPL' as the HIPL installation directory"

if [ ! -d "$HIPL" ];then
  echo "** Error: '$HIPL' is not a directory" 
  exit 1
fi

./autogen.sh
./configure
make dist

echo "** Package building root is '$PKGROOT'" 
cd "$PKGROOT"

PKGDIR=$PKGROOT/hipl-userspace-$VERSION

cd $PKGROOT
rm -rf $PKGROOT/hipl-userspace-$VERSION
tar xfz $HIPL/hipl-main.tar.gz
mv -v hipl-main $PKGDIR

cd "$PKGDIR"
cp -v $HIPL/autogen.sh .

if ! mkdir -p linux/include/net;then
  echo "** Error creating directory '$PKGDIR/linux/include/net'"
  error_cleanup
fi
cp -v $HIPL/linux/include/net/hip.h linux/include/net/

find -name '.arch*' | xargs rm -rf

echo "** Creating source package $PKGROOT/hipl-userspace${SUFFIX}.tgz"
tar czpf $PKGROOT/hipl-userspace${SUFFIX}.tgz .
ls -l $PKGROOT/hipl-userspace${SUFFIX}.tgz

cat <<EOF
**
** Finished building the source package
**
** Now login as root and copy $PKGROOT/hipl-userspace${SUFFIX}.tgz to
** /usr/src/rpm/SOURCES. After that run command:
** rpmbuild -ba $PKGROOT/hipl-userspace${SUFFIX}.spec
** When everyting is finished successfully, there will be RPM package
** /usr/src/rpm/RPMS/i386/hipl-userspace${SUFFIX}.i386.rpm
EOF

error_cleanup
