#!/bin/sh -xv

MAJOR=1
MINOR=0
VERSION="$MAJOR.$MINOR"
RELEASE=1
SUFFIX="-$VERSION.$RELEASE"
NAME=hipl
PKGROOT=$PWD
HIPL=$PWD/..
PKGDIR=$PKGROOT/${NAME}-$VERSION

#error_cleanup()
#{
# if [ -n "$PKGDIR" -a -d "$PKGDIR" ];then
#   echo "removing '$PKGDIR'"
#   rm -rf "$PKGDIR"
# fi
#}

echo "** Creating the directory structure and files for building the"
echo "** source package needed for RPM package containing HIPL"
echo "** user space software"
echo "**"
echo "** Version $VERSION (release $RELEASE)"
echo "**"

echo "** Using directory '$HIPL' as the HIPL installation directory"

if [ ! -d "$HIPL" ];then
  echo "** Error: '$HIPL' is not a directory" 
  exit 1
fi

make dist

echo "** Package building root is '$PKGROOT'" 
tar xfz $HIPL/${NAME}-main.tar.gz
mv -v ${NAME} $PKGDIR

echo "** Creating source package $PKGROOT/${NAME}${SUFFIX}.tar.gz"
tar czf $PKGROOT/hipl${SUFFIX}.tar.gz $PKGDIR
ls -l $PKGROOT/hipl${SUFFIX}.tar.gz
mv $PKGROOT/hipl${SUFFIX}.tar.gz $PKGROOT/test/packaging/SOURCES

rpmbuild -ba --buildroot $PKGROOT/test/packaging $PKGROOT/test/packaging/hipl.spec

error_cleanup
