#!/bin/sh
# HIPL autobuild script for periodic compilation tests.
# The name of the branch to test needs to be passed as the first parameter.
#
# If the HIPL_NOTIFICATION_EMAIL environment variable is set to a suitable value
# for the user running this script, then email will be sent in case of failure.

BRANCH_NAME=$1
BRANCH_LOCATION=$2

BUILD_DIR=$HOME/tmp/hipl_autobuild
BRANCH_URL=http://hipl.hiit.fi/hipl/hipl-bzr/$BRANCH_LOCATION
CHECKOUT_DIR=$BUILD_DIR/$(date +"%Y-%m-%d-%H%M")_$BRANCH_NAME
BRANCH_REVISION=$(bzr revno -q $BRANCH_URL)
BRANCH_REVISION_FILE=$BUILD_DIR/HIPL_REVISION_$BRANCH_NAME
AUTOBUILD_REVISION=$(cat $BRANCH_REVISION_FILE)

# helper functions
run_program()
{
    $@ > log.txt 2>&1
    if [ $? -eq 0 ] ; then
        rm -f log.txt
        return 0
    else
        SUBJECT="[$BRANCH_NAME] [autobuild] failing command: $@"
        test $HIPL_NOTIFICATION_EMAIL &&
            mailx -s "$SUBJECT" $HIPL_NOTIFICATION_EMAIL < log.txt
        cleanup 1
    fi
}

cleanup()
{
    chmod -R u+rwx "$CHECKOUT_DIR"
    rm -rf "$CHECKOUT_DIR"
    echo $BRANCH_REVISION > $BRANCH_REVISION_FILE
    exit $1
}

compile()
{
    run_program ./autogen.sh &&
        run_program ./configure --prefix=$(pwd)/local_install $@ &&
        run_program make -j16 &&
        run_program make -j16 distcheck &&
        run_program make install
}

test $BRANCH_REVISION = $AUTOBUILD_REVISION && exit 0

bzr checkout -q --lightweight $BRANCH_URL $CHECKOUT_DIR

cd "$CHECKOUT_DIR"

# Compile HIPL in different configurations
# vanilla configuration
compile
# The following configuration is commented out until HIPL is fixed
# PISA configuration
#compile --disable-agent --disable-cookie --disable-pfkey --disable-rvs --disable-hipproxy --disable-altsep --enable-privsep --disable-i3 --disable-opportunistic --disable-dht --disable-blind --disable-profiling --enable-debug --enable-midauth --disable-performance --disable-demo
compile --disable-agent --disable-cookie --disable-pfkey --disable-hipproxy --disable-altsep --enable-privsep --disable-i3 --disable-opportunistic --disable-dht --disable-blind --disable-profiling --enable-debug --enable-midauth --disable-performance --disable-demo
# Alternative path to vanilla
compile --enable-agent --enable-cookie --disable-hipproxy --enable-openwrt --enable-altsep --disable-privsep --enable-i3 --disable-opportunistic --disable-dht --enable-blind --enable-profiling --enable-ecdsa --disable-debug --enable-midauth --enable-performance --enable-demo


cleanup 0
