#!/bin/sh
# HIPL autobuild script for periodic compilation tests.
# The name of the branch to test needs to be passed as the first parameter.
#
# If the HIPL_NOTIFICATION_EMAIL environment variable is set to a suitable value
# for the user running this script, then email will be sent in case of failure.

BRANCH_NAME=$1
BRANCH_LOCATION=$2

BUILD_DIR=$HOME/tmp/hipl_autobuild
BRANCH_URL=http://hipl.hiit.fi/hipl/hipl-bzr/$BRANCH_LOCATION
CHECKOUT_DIR=$BUILD_DIR/$(date +"%Y-%m-%d-%H%M")_$BRANCH_NAME
BRANCH_REVISION=$(bzr revno -q $BRANCH_URL)
BRANCH_REVISION_FILE=$BUILD_DIR/HIPL_REVISION_$BRANCH_NAME
AUTOBUILD_REVISION=$(cat $BRANCH_REVISION_FILE)
AUTOBUILD_SCRIPT="$CHECKOUT_DIR/tools/hipl_autobuild"

# helper functions
run_program()
{
    $@ > log.txt 2>&1
    if [ $? -eq 0 ] ; then
        rm -f log.txt
        return 0
    else
        test $HIPL_NOTIFICATION_EMAIL &&
            mailx -s "autobuild failed: @$1 output:" $HIPL_NOTIFICATION_EMAIL < log.txt
        cleanup 1
    fi
}

cleanup()
{
    rm -rf "$CHECKOUT_DIR"
    echo $BRANCH_REVISION > $BRANCH_REVISION_FILE
    exit $1
}

compile()
{
    run_program ./autogen.sh &&
        run_program ./configure --prefix=$(pwd)/local_install $@ &&
        run_program make -j16 &&
        run_program make -j16 distcheck &&
        run_program make install
}

test $BRANCH_REVISION = $AUTOBUILD_REVISION && exit 0

bzr checkout -q --lightweight $BRANCH_URL $CHECKOUT_DIR

# Perform a self-update if the autobuild script in the repository has changed.
# Only do this when running as the autobuild user so as not to interfere with
# manual testing of this script.
if test "$HIPL_AUTOBUILDER" = "yes" && ! cmp -s "$0" "$AUTOBUILD_SCRIPT" ; then
    cp "$AUTOBUILD_SCRIPT" $0
    rm -rf "$CHECKOUT_DIR"
    exec $0
fi

cd "$CHECKOUT_DIR"

# Compile HIPL in different configurations
compile
# The following configuration is commented out until HIPL is fixed
#compile --disable-rvs --disable-ice --disable-hipproxy --disable-opportunistic --disable-savaipopt
#compile --enable-agent --enable-cookie --enable-pfkey --enable-cert --disable-rvs --disable-ice --disable-hipproxy --enable-openwrt --enable-altsep --enable-i3 --disable-privsep --disable-opportunistic --disable-savaipopt --disable-dht --enable-blind --enable-libinet6 --enable-profiling --enable-ecdsa --disable-debug --enable-midauth --enable-performance --enable-demo


cleanup 0
